### ISSUE TITLE
Model.scenarios not producing output

### ISSUE THREAD

**Issue by wijdan225** [jason-ash/pyesg#75] opened 2020-11-13 16:45 UTC
Hi Jason - this is a newbie question. I'm trying to run the following code in Jupyter notebook but I'm not getting any output...it just sits there like I never pressed run.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
import pyesg

model = pyesg.GeometricBrownianMotion(mu = 0.05, sigma = 0.2)

x0 = 100
dt = 1
n_scenarios = 1000
n_steps = 60
random_state = 123

results = model.scenarios(x0, dt, n_scenarios, n_steps, random_state)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
I've tried other code to test there's nothing else wrong but I don't think there is. For example, when I run...

import pyesg

mu = 0.05
sigma = 0.2
x0 = 100
dt = 10

pyesg.GeometricBrownianMotion(mu, sigma).expectation(x0, dt)

...I get:
array([134.98588076])

Can you help?! I'm quite new to Python so I'm pretty sure I'm just make an obvious mistake somewhere. 

Wijdan

**Comment by jason-ash** [comment] 2020-11-14 03:41
Closing as a duplicate of #74.

**Closed by jason-ash** 2020-11-14 03:41 UTC
